config/routes.rb
Rails.application.routes.draw do
  # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users
  root to: "pages#home"
  get "/dashboard", to: "pages#dashboard"
  get "/leaderboard", to: "pages#leaderboard"
  get "/users/:id", to: "pages#user"

  # post "/habits/:id/counter", to: "habits#counter", as: :counter

  resources :habits do
    patch :update, on: :member
    member do
      put :check_as_done
    end
  end

  resources :friendships

  # get 'users/:id/request', to: "friendships#new"
  # post 'users/:id', to: 'friendships#create', as: 'request_friendship'
  # patch 'friendships/:id', to: "friendships#accept"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
<%# link to home %>
  <%= link_to dashboard_path do %>
    <i class="fa-solid fa-house"></i>
  <% end %>
<%# link to leaderboard %>
    <%= link_to leaderboard_path do %>
    <i class="fa-solid fa-trophy"></i>
  <% end %>
<%# link to habits show or index %>
      <%= link_to new_habit_path do %>
    <i class="fa-solid fa-circle-plus"></i>
  <% end %>
<%# link to friendships overview %>
      <%= link_to new_friendship_path do %>
    <i class="fa-solid fa-handshake"></i>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "hybit_logo.jpg" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <% if current_user.photo.attached? %>
              <%= cl_image_tag(current_user.photo.key, crop: :thumb, gravity: :face, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
            <% else %>
              <%= image_tag "user_b.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%# Hieronder opties later aanvullen %>
              <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>