config/routes.rb
Rails.application.routes.draw do
  # Sidekiq Web UI, only for admins.
  require "sidekiq/web"
  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users
  root to: "pages#home"
  get "/dashboard", to: "pages#dashboard"
  get "/leaderboard", to: "pages#leaderboard"
  get "/users/:id", to: "pages#user"

  # post "/habits/:id/counter", to: "habits#counter", as: :counter

  resources :habits do
    patch :update, on: :member
    member do
      put :check_as_done
    end
  end

  resources :friendships

  # get 'users/:id/request', to: "friendships#new"
  # post 'users/:id', to: 'friendships#create', as: 'request_friendship'
  # patch 'friendships/:id', to: "friendships#accept"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/habit.rb
class Habit < ApplicationRecord
  belongs_to :user
  belongs_to :buddy, class_name: 'User', optional: true
  has_many :habitlogs
  before_create :new_habit_set_habit_counts
  before_create :new_habit_set_due_date
  # before_update :reset_due_date
  # before_update :set_habit_counts
  # include ApplicationHelper

  validates :name, presence: true
  validates :frequency_number, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 7 }, presence: true
  validates :frequency_variable, inclusion: { in: %w[day week month year], message: "%{value} is not a valid unit" }
  validates :importance_level, presence: true, inclusion: { in: [1, 2, 3, 4, 5], message: "Please choose a level from 1 to 5" }
  validate :frequency_number_present, if: :importance_level_1?
  validate :frequency_variable_present, if: :importance_level_1?
  validate :contact_details_present, if: :importance_level_3?
  validate :public_shame_present, if: :importance_level_4?
  validate :bank_connection_present, if: :importance_level_5?

  ### methods are only called before new_habits are created
  def new_habit_set_habit_counts
    self.habitcount = frequency_number
    self.habitcount_day = frequency_number
    self.habitcount_week = frequency_number
    self.habitcount_month = frequency_number
    self.habitcount_year = frequency_number
  end

  def new_habit_set_due_date
    case self.frequency_variable
    when "week"
      self.due_date = DateTime.now + 7.days
    when "day"
      self.due_date = DateTime.now + 1.day
    when "month"
      self.due_date = DateTime.now + 1.month
    when "year"
      self.due_date = DateTime.now + 1.year
    end
  end

  # this method is flawless #############
  def in_timeframe?(check)
    case timeframe
    when "morning"
      (6..11).cover?(check.hour)
    when "afternoon"
      (11..17).cover?(check.hour)
    when "evening"
      (17..24).cover?(check.hour)
    when "day"
      (06..24).cover?(check.hour)
    end
  end
  # ###########################

  private

  def importance_level_1?
    importance_level >= 1
  end

  def importance_level_3?
    importance_level > 2
  end

  def importance_level_4?
    importance_level > 3
  end

  def importance_level_5?
    importance_level > 4
  end

  def contact_details_present
    errors.add(:contact_details, "- We need this in order to notify your buddy of your lack of progress") unless contact_details.present?
  end

  def public_shame_present
    errors.add(:public_shame, "- We can't threaten you with public shame if we cannot broadcast your failure on your chosen social-medium") unless public_shame.present?
  end

  def bank_connection_present
    errors.add(:bank_connection, "- We need this to make you pay for continuously ignoring the reminders of your habit") unless bank_connection.present?
  end

  def frequency_number_present
    errors.add(:frequency_number, "- Please tell us how many times you want to do this") unless frequency_number.present?
  end

  def frequency_variable_present
    errors.add(:frequency_variable, "- Please tell us how often you want to do this") unless frequency_variable.present?
  end
end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController
  before_action :habit_params, only: %i[create update destroy]
  before_action :set_habit, only: %i[show edit update check_as_done destroy]
  before_action :set_friends, only: %i[new edit update destroy]
  before_action :set_habit_dates_to_user_local_time, only: %i[check_as_done]
  # include ApplicationHelper

  def index
    @habit = Habit.all
  end

  def show
    # @habit = Habit.find(params[:id])
    if @habit.buddy.present?
      @buddy = User.find(@habit.buddy_id)
    end
  end

  def new
    @habit = Habit.new
  end

  def edit
  end

  def create
    @habit = Habit.new(habit_params)
    @habit.user = current_user
    if @habit.save
      redirect_to habit_path(@habit.id), notice: 'Habit was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @habit.update(habit_params)
    # UpdateHabitDuedatesJob.perform_later(@habit.id)
    if @habit.save
      flash[:notice] = "Habit succesfully updated"
      redirect_to habit_path(@habit)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    if @habit.destroy
      redirect_to dashboard_path, notice: "Deleted habit"
    else
      flash[:notice] = "You can't check delete this habit right now!"
    end
  end

  # # Seems to work fine, hard to test bc of time passing... ##
  # if the habitcount_day or week or month etc is not 0 yet, after each button click it saves it untill the reset time;
  # which is defined for current_user's time: 05.00 in the morning.

  # when habitcount is clicked to 0; ActiveJob will handle (at beginning of day/week/month/year + 3.hours) so at 03.00 in the morning:
  # adding points to habit.points, thus saving the frequency-number to habit; reset
  # setting new duedate to +1day/week/month/year after the specified duedate when active job starts running
  # sets button again to false

  def check_as_done
    @habit = Habit.find(params[:id])
    @check = local_user_time(Time.now)
    if @habit.in_timeframe?(@check)
      if @habit.done == false
        time_of_click = Time.now
        @habit.update(done: true, save_click_time: time_of_click)
        case @habit.frequency_variable
        when "day"
          @habit.decrement!(:habitcount_day)
          if @habit.habitcount_day.positive?
            HabitButtonResetJob.set(wait_until: @reset_time).perform_later(@habit.id, @reset_time)
          elsif @habit.habitcount_day.zero?
            @habit.increment!(:streak_count)
            HabitStreakResetJob.set(wait_until: @due_date_day).perform_later(@habit.id, @due_date_day)
          end
        when "week"
          @habit.decrement!(:habitcount_week)
          if @habit.habitcount_week.positive?
            HabitButtonResetJob.set(wait_until: @reset_time).perform_later(@habit.id, @reset_time)
          elsif @habit.habitcount_week.zero?
            @habit.increment!(:streak_count)
            HabitStreakResetJob.set(wait_until: @due_date_week).perform_later(@habit.id, @due_date_week)
          end
        when "month"
          @habit.decrement!(:habitcount_month)
          if @habit.habitcount_month.positive?
            HabitButtonResetJob.set(wait_until: @reset_time).perform_later(@habit.id, @reset_time)
          elsif @habit.habitcount_month.zero?
            @habit.increment!(:streak_count)
            HabitStreakResetJob.set(wait_until: @due_date_month).perform_later(@habit.id, @due_date_month)
          end
        when "year"
          @habit.decrement!(:habitcount_year)
          if @habit.habitcount_year.positive?
            HabitButtonResetJob.set(wait_until: @reset_time).perform_later(@habit.id, @reset_time)
          elsif @habit.habitcount_year.zero?
            @habit.increment!(:streak_count)
            HabitStreakResetJob.set(wait_until: @due_date_year).perform_later(@habit.id, @due_date_year)
          end
        end
      else
        flash[:notice] = "You can't check this habit off right now!"
      end
    else
      # give error saying request to press has timed out
      case @habit.timeframe
      when "day"
        flash[:notice] = "Time is: #{local_user_time(Time.now).strftime("%H:%M")} - you can only check this habit as done between 06:00 and 23:59"
      when "morning"
        flash[:notice] = "Time is: #{local_user_time(Time.now).strftime("%H:%M")} - You can only check this habit as done between 06:00 and 11:00"
      when "afternoon"
        flash[:notice] = "Time is: #{local_user_time(Time.now).strftime("%H:%M")} - You can only check this habit as done between 11:00 and 17:00"
      when "evening"
        flash[:notice] = "Time is: #{local_user_time(Time.now).strftime("%H:%M")} - You can only check this habit as done between 17:00 and 23:59"
      else
        flash[:notice] = "You can't check off this habit at this time"
      end
    end
    redirect_to habit_path(@habit)
  end

  private

  def habit_params
    params.require(:habit).permit(:name, :category, :start_date, :end_date, :frequency_number, :frequency_variable, :importance_level, :contact_details, :public_shame, :bank_connection, :done, :habit_public, :motivation, :motivation_public, :buddy_id, :streak_count, :timeframe)
  end

  def set_habit
    @habit = Habit.find(params[:id])
  end

  def set_friends
    @mutual_friends = User.where(id: current_user.friends && current_user.friendships.where(mutual: true).pluck(:friend_id))
  end

  ## sets all things for the logic of check_as_done - that time = always user's local-time ##
  ## uses helper in app/helpers/application_helper.rb
  def set_habit_dates_to_user_local_time
    local = local_user_time(@habit.due_date)
    local_time = local_user_time(Time.now.tomorrow.beginning_of_day)

    @due_date_day = (local.beginning_of_day + 3.hours).to_datetime
    @due_date_week = (local.beginning_of_week + 3.hours).to_datetime
    @due_date_month = (local.beginning_of_month + 3.hours).to_datetime
    @due_date_year = (local.beginning_of_year + 3.hours).to_datetime
    @reset_time = (local_time + 5.hours).to_datetime
  end

  # def define_due_date(habit)
  #   case habit.frequency_variable
  #   when "day"
  #     return habit.start_date + 1.day
  #   when "week"
  #     return habit.start_date + 7.days
  #   when "month"
  #     return habit.start_date + 30.days
  #   when "year"
  #     return habit.start_date + 365.days
  #   end
  # end

  # def index
  #   if params[:query].present?
  #     sql_query = <<~SQL
  #       owned_habits.name @@ :query
  #       OR owned_habits.start_date @@ :query
  #       OR owned_habits.importance_level @@ :query
  #       OR owned_habits.category @@ :query
  #     SQL
  #     @owned_habits = Habit.where(sql_query, query: "%#{params[:query]}%")
  #   else
  #     @owned_habits = Habit.all
  # end

  # def habit_done
  #   # @habit.streak_count = @habit.streak_count + 1
  #   @habit.update(streak_count: @habit.streak_count + 1)
  #   # @habit.update(done: :true)
  #   if @habit.save
  #     redirect_to habit_path(@habit)
  #   else
  #     flash[:notice] = "Habit not done"
  #   end
  # end

  # def counter (code for Background task through Sidekiq)
  #   @habit = Habit.find(params[:id])
  #   # if @habit.done == true
  #   #   @habit.streak_count += 1
  #   # elsif @habit.done == false
  #   #   if @habit.importance_level == 1 # only applies to # level 1 habits
  #   #     @habit.streak_count = 0
  #   #   else # applies to habits with level 2 and up
  #   #     if @habit.streak_count.positive? # first time # false
  #   #       @habit.streak_count = 0
  #   #     elsif @habit.streak_count <= 0 # second time # false
  #   #       @habit.streak_count += 1
  #   #     end
  #   #   end
  #   # end
  #   @habit.save
  # end
end

app/views/habits/create.html.erb
<h1>Habits#create</h1>
<p>Find me in app/views/habits/create.html.erb</p>

app/views/habits/destroy.html.erb
<h1>Habits#destroy</h1>
<p>Find me in app/views/habits/destroy.html.erb</p>

app/views/habits/index.html.erb
<h1>Habits#index</h1>
<p>Find me in app/views/habits/index.html.erb</p>

app/views/habits/show.html.erb
<div class="container">

  <h5>Habit:</h5>
  <h2><strong><%= @habit.name %></strong></h2>

  <div class="card-show">

    <% if @habit.category == "Productivity" %>
      <%= image_tag "hybit-productivity.png" %>
    <% elsif @habit.category == "Energy" %>
      <%= image_tag "hybit-energy.png" %>
    <% elsif @habit.category == "Relationships" %>
      <%= image_tag "hybit-relationships.png" %>
    <% elsif @habit.category == "Order" %>
      <%= image_tag "hybit-order.png" %>
    <% elsif @habit.category == "Purpose" %>
      <%= image_tag "hybit-purpose.png" %>
    <% elsif @habit.category == "Creativity" %>
      <%= image_tag "hybit-creativity.png" %>
    <% elsif @habit.category == "Recharging" %>
      <%= image_tag "hybit-recharge.png" %>
    <% else %>
      <%= image_tag "hybit-check.png" %>
    <% end %>

    <div class="card-show-info">
      <% if @habit.streak_count <= 0 %>
        <h5> <strong>Currently no streak...</strong></h5><h6>Get back on track! 💪 </h6>
      <% else %>
        <h5>🔥 <strong><%= @habit.streak_count%> <%= @habit.frequency_variable %></strong> streak 🔥 <h5>
      <% end %>
      <h6>Importance level: <%= @habit.importance_level %></h6>
    </div>

  </div>

  <% case @habit.importance_level %>
    <% when 1 %>
    <p class="field">
      <i class="fa-solid fa-circle" aria-hidden="true"></i>
      <i class="fa-regular fa-circle" aria-hidden="true"></i>
      <i class="fa-regular fa-circle" aria-hidden="true"></i>
      <i class="fa-regular fa-circle" aria-hidden="true"></i>
      <i class="fa-regular fa-circle" aria-hidden="true"></i></p>
    <% when 2 %>
    <p class="field">
      <i class="fa-solid fa-circle" aria-hidden="true"></i>
      <i class="fa-solid fa-circle" aria-hidden="true"></i>
      <i class="fa-regular fa-circle" aria-hidden="true"></i>
      <i class="fa-regular fa-circle" aria-hidden="true"></i>
      <i class="fa-regular fa-circle" aria-hidden="true"></i></p>
    <% when 3 %>
    <p class="field">
      <i class="fa-solid fa-circle" aria-hidden="true"></i>
      <i class="fa-solid fa-circle" aria-hidden="true"></i>
      <i class="fa-solid fa-circle" aria-hidden="true"></i>
      <i class="fa-regular fa-circle" aria-hidden="true"></i>
      <i class="fa-regular fa-circle" aria-hidden="true"></i></p>
    <% when 4 %>
    <p class="field">
      <i class="fa-solid fa-circle" aria-hidden="true"></i>
      <i class="fa-solid fa-circle" aria-hidden="true"></i>
      <i class="fa-solid fa-circle" aria-hidden="true"></i>
      <i class="fa-solid fa-circle" aria-hidden="true"></i>
      <i class="fa-regular fa-circle" aria-hidden="true"></i></p>
    <% when 5 %>
    <p class="field">
    <i class="fa-solid fa-circle" aria-hidden="true"></i>
    <i class="fa-solid fa-circle" aria-hidden="true"></i>
    <i class="fa-solid fa-circle" aria-hidden="true"></i>
    <i class="fa-solid fa-circle" aria-hidden="true"></i>
    <i class="fa-solid fa-circle" aria-hidden="true"></i></p>
  <% end %>
  <p class="field"><i class="fa-regular fa-calendar"></i><strong>    Started </strong> on the <strong><%= local_user_time(@habit.start_date).strftime("%-d#{local_user_time(@habit.start_date).day.ordinal}")%></strong> of <strong><%= local_user_time(@habit.start_date).strftime("%B '%y").downcase %></strong></p>
  <% if @habit.end_date? %>
    <p class="field"><i class="fa-regular fa-calendar"></i><strong>    Tracking progress </strong> until <strong><%= local_user_time(@habit.end_date).strftime("%b %-d#{local_user_time(@habit.end_date).day.ordinal}")%></strong> of <strong><%= local_user_time(@habit.end_date).strftime("'%y") %></strong></p>
  <% else %>
    <p class="field"><i class="fa-regular fa-calendar"></i><strong>    Tracking progress </strong> until <strong>∞</strong> </p>
  <% end %>

  <% if @habit.frequency_number > 1 %>
    <p class="field"><i class="fa-solid fa-repeat"></i>    do it <strong><%= @habit.frequency_number %> </strong> times per <strong><%= @habit.frequency_variable %></strong></p>
  <% else %>
    <p class="field"><i class="fa-solid fa-repeat"></i>    do it <strong><%= @habit.frequency_number %> </strong> time per <strong><%= @habit.frequency_variable %></strong></p>
  <% end %>

  <% if @habit.due_date.nil? %>
    <p class="field"><i class="fa fa-hourglass-end"></i>    no <strong>due date </strong> is <strong></strong> set</p>
  <% elsif Time.now < @habit.due_date %>
    <% case @habit.timeframe %>
    <% when "day" %>
      <p class="field"><i class="fa-regular fa-bell"></i>    do it before <strong>midnight</strong> </p>
    <% when "morning" %>
      <p class="field"><i class="fa-regular fa-bell"></i>    do it before <strong>11:00</strong> </p>
    <% when "afternoon" %>
      <p class="field"><i class="fa-regular fa-bell"></i>    do it before <strong>17:00</strong> </p>
    <% when "evening" %>
      <p class="field"><i class="fa-regular fa-bell"></i>    do it before <strong>23:59</strong> </p>
    <% end %>
  <% else %>
    <% case @habit.timeframe %>
    <% when "day" %>
      <p class="field"><i class="fa fa-exclamation-triangle"></i>    missed the deadline...</p>
    <% when "morning" %>
      <p class="field"><i class="fa fa-exclamation-triangle"></i>    missed the deadline...</p>
    <% when "afternoon" %>
      <p class="field"><i class="fa fa-exclamation-triangle"></i>    missed the deadline...</p>
    <% when "evening" %>
      <p class="field"><i class="fa fa-exclamation-triangle"></i>    missed the deadline...</p>
    <% end %>
  <% end %>

  <% if @habit.done? %>
    <% if @habit.save_click_time? %>
      <% if local_user_time(@habit.save_click_time).day == Date.today.day && local_user_time(@habit.save_click_time).month == Date.today.month %>
        <p class="field"><i class="fa-solid fa-check-circle"></i>    done <strong>today</strong> at <strong><%= local_user_time(@habit.save_click_time).strftime("%H:%M")%></strong> </p>
      <% elsif local_user_time(@habit.save_click_time).day == Date.yesterday.day && local_user_time(@habit.save_click_time).month == Date.yesterday.month %>
        <p class="field"><i class="fa-solid fa-check-circle"></i>    done <strong>yesterday</strong> at <strong><%= local_user_time(@habit.save_click_time).strftime("%H:%M")%></strong> </p>
      <% else %>
        <p class="field"><i class="fa-solid fa-check-circle"></i>    done at <strong><%= local_user_time(@habit.save_click_time).strftime("%H:%M")%></strong> on the <strong><%= local_user_time(@habit.save_click_time).strftime("%-d#{local_user_time(@habit.save_click_time).day.ordinal}")%></strong> of <strong><%= local_user_time(@habit.save_click_time).strftime("%B").downcase %></strong> </p>
      <% end %>
    <% else %>
      <p class="field"><i class="fa-solid fa-check-circle"></i>    done in time! </strong></p>
    <% end %>
  <% else %>
    <% case @habit.timeframe %>
      <% when "day" %>
        <p class="field"><i class="fa-regular fa-check-circle"></i>    during the <strong>day</strong> before <strong>midnight</strong> </p>
      <% when "morning" %>
        <p class="field"><i class="fa-regular fa-check-circle"></i>    in the <strong>morning</strong> between <strong> 06:00 </strong> and <strong>11:00</strong> </p>
      <% when "afternoon" %>
        <p class="field"><i class="fa-regular fa-check-circle"></i>    in the <strong>afternoon</strong> between <strong> 11:00 </strong> and <strong>17:00</strong> </p>
      <% when "evening" %>
        <p class="field"><i class="fa-regular fa-check-circle"></i>    in the <strong>evening</strong> between <strong> 17:00 </strong> and <strong>01:00</strong> </p>
      <% end %>
  <% end %>

  <% if @habit.due_date? %>
    <% case @habit.frequency_variable %>
      <% when "day" %>
        <% if @habit.habitcount_day == 0 %>
          <p class="field"><i class="fa fa-rocket"></i>    you hit your goal of <strong><%= @habit.frequency_number %></strong> x per <strong><%= @habit.frequency_variable %></strong>!</strong></p>
        <% else %>
          <p class="field"><i class="fa fa-hourglass-end"></i>    <strong>still</strong> have to <strong>do it <%= @habit.habitcount_day %> x</strong> before <strong><%= local_user_time(@habit.due_date).strftime("%-d")%> <%= local_user_time(@habit.due_date).strftime("%b '%y").upcase %></strong></p>
        <% end %>
      <% when "week" %>
        <% if @habit.habitcount_week == 0 %>
          <p class="field"><i class="fa fa-rocket"></i>    you hit your goal of <strong><%= @habit.frequency_number %></strong> x per <strong><%= @habit.frequency_variable %></strong>!</strong></p>
        <% else %>
        <p class="field"><i class="fa fa-hourglass-end"></i>    <strong>still</strong> have to <strong>do it <%= @habit.habitcount_week %> x </strong> before <strong><%= local_user_time(@habit.due_date).strftime("%-d")%> <%= local_user_time(@habit.due_date).strftime("%b '%y").upcase %></strong></p>
        <% end %>
      <% when "month" %>
        <% if @habit.habitcount_month == 0 %>
          <p class="field"><i class="fa fa-rocket"></i>    <strong>goal met</strong>: you did it <strong><%= @habit.frequency_number %></strong> x this <strong><%= @habit.frequency_variable %></strong>!</strong></p>
        <% else %>
          <p class="field"><i class="fa fa-hourglass-end"></i>    <strong>still</strong> have to <strong>do it <%= @habit.habitcount_month %> x </strong> before <strong><%= local_user_time(@habit.due_date).strftime("%-d")%> <%= local_user_time(@habit.due_date).strftime("%b '%y").upcase %></strong></p>
        <% end %>
      <% when "year" %>
        <% if @habit.habitcount_year == 0 %>
          <p class="field"><i class="fa fa-rocket"></i>    you hit your goal of <strong><%= @habit.frequency_number %></strong> x per <strong><%= @habit.frequency_variable %></strong>!</strong></p>
        <% else %>
          <p class="field"><i class="fa fa-hourglass-end"></i>    <strong>still</strong> have to <strong>do it <%= @habit.habitcount_year %> x </strong> before <strong><%= local_user_time(@habit.due_date).strftime("%-d")%> <%= local_user_time(@habit.due_date).strftime("%b '%y").upcase %></strong></p>
        <% end %>
      <% end %>
  <% else %>
    <p class="field"><i class="fa fa-hourglass-end"></i>    <strong></strong> not set</p>
  <% end %>





  <div class="btn btn-primary <%= @habit.done == true ? "disabled" : "" %>" style="box-shadow: none">
    <%= form_tag check_as_done_habit_path(@habit), method: :put do %>
      <%= submit_tag @habit.done == true ? 'Already done' : 'Did it!', class: 'btn btn-primary' %>
    <% end %>
  </div>

<hr>

  <div class="card-friendship-habit">
    <h6><i><strong>Remember why?</strong></i></h6>
    <h6><%= @habit.motivation %> </h6>
  </div>

  <% if @habit.buddy.present? %>
    <div class="card-friendship">
      <h4>Your accountabilibuddy: <strong><%= @buddy.nickname %></strong></h4>
      <%= link_to "/users/#{@buddy.id}" do %>
        <% if @buddy.photo.attached? %>
          <%= cl_image_tag(@buddy.photo.key, crop: :thumb, gravity: :face, class: "avatar-large") %>
        <% else %>
          <%= image_tag "user_b.png", class: "avatar" %>
        <% end %>
      <% end %>
    </div>
  <% end %>
<hr>
  <div class="form-edit" style="box-shadow: none">
    <%= link_to "Edit", edit_habit_path, class: "btn btn-secondary" %>
    <%= link_to "Delete", habit_path(@habit), class: "btn btn-secondary", data: {turbo_method: :delete, turbo_confirm: "sure?"} %>
    <%# <%= link_to "Back", dashboard_path, class:"btn btn-secondary" %>
  </div>
</div>

app/views/habits/update.html.erb
<h1>Habits#update</h1>
<p>Find me in app/views/habits/update.html.erb</p>